name: dart_encryption
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  encrypt: ^5.0.0
  crypto: ^3.0.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
